#theme: jekyll-theme-slate

title:               'Matthew Ballance'
tagline:             ''
description:         ''
url:                 '.'
baseurl:             '.'
paginate:            5
google_analytics_id: G-D4CQR7PB0Z

# About/contact
author:
    name:              Matthew Ballance
    url:               http://mballance.github.io
    email:             matt.ballance@gmail.com

github:
    repo: http://github.com/mballance

plugins:
    - jekyll-paginate


